In [2]:
import numpy as np

In [4]:
arr_1d=np.array([1,2,3])
print(arr_1d)

arr_2d=np.array([[12,3,4],[1,2,4]])
print(arr_2d)

[1 2 3]
[[12  3  4]
 [ 1  2  4]]


In [8]:
import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)   

start1=time.time()
py_array=np.arange(100000)*2
print("Time takenfor pyhton array",time.time()-start1)


 List operation time:  0.27527880668640137
Time takenfor pyhton array 0.0013456344604492188


### Creating array from scratch


In [15]:
zeros=np.zeros((3,4))
print("zero arrays \n", zeros)

#creating matrix for ones
ones=np.ones((3,4))
print(ones)

full=np.full((2,2),7)
print(full)

zero arrays 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[7 7]
 [7 7]]


### Convertinga multi dimensional array into 1D

In [6]:
''' ravel()-> changes in the orignal array and displays
flatten()-> only displays it and do not make changes in the original array
'''
import numpy as np
arr_2d = np.array([[2, 4, 6],
                 [2, 5, 6]])
print(arr_2d.ravel())
print(arr_2d.flatten())



[2 4 6 2 5 6]
[2 4 6 2 5 6]


### converting 1d list into 2d 


In [12]:
import numpy as np
array_1d=np.array([1,5,3,4,5,6])
print(array_1d.reshape(2,3))



[[1 5 3]
 [4 5 6]]


### Adding elements in an array

In [ ]:

'''
(array name,index ,value,axis=)
axis 0 if rows
1 if to add in columns
'''
arr=np.array([1,2,3,4])
new_arr=np.insert(arr,2,100)
print(arr)
print(new_arr)
#append option to add an element at the end of the array
#APPENDING IN AN ARRAY


[1 2 3 4]
[  1   2 100   3   4]


### Joinning two arrays

In [ ]:
'''
np.concetate((array 1 ,array2),axis)
axis 0->vertical 
axis 1-> horizontal
'''

arr1=np.array([1,2,3])
arr2=np.array([6,7,8])
arr3=np.concatenate((arr1,arr2))
print(arr3)  #yhis would join the two arrays in the deafault horizontal

[1 2 3 6 7 8]


### Removing element of an array

In [7]:
#np.delete(array ,index,axis=none)
import numpy as np
array1=([1,2,34,5])
arr1_=np.delete(array1,0,axis=None)
print(array1)
print(arr1_)

[1, 2, 34, 5]
[ 2 34  5]


### stacking arrays

In [8]:
# vstack() for vertical stakking 
#hstack() for horizontal stacking

import numpy as np
arr1=np.array([1,2,3])

arr2=np.array([6,7,8])
print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))



[[1 2 3]
 [6 7 8]]
[1 2 3 6 7 8]


### splitting array

In [11]:
#np.split()-> equal
#np.vsplit()-> vertical
#np.hsplit()->horizontal
import numpy as np
array4=np.array([12,4,5,6,7,8])
print(np.split(array4,6))



[array([12]), array([4]), array([5]), array([6]), array([7]), array([8])]


### broadcasting

In [ ]:
'''
1.matching dimesnions data easy to do aritchemtic operations with coz of the same size
2.expanding single elements for example [1,2,3] +2
-----> answer/output would be 2,4,5
3.incompetable shapes -> throws error in case of different shapes of  array like [1,2] cannot be added with [1,23,5,6,7]

'''
#create a 2x3 matrix
matrix=np.array(([1,2,3],[2,3,5]))
#create a 1d matrix
oned_matrix=np.array([2,3,3])
result=matrix+oned_matrix
print(result)

#broadcasting expand small arrays into large one 
#faster than loops 
#VECTORIZATION ----> appplies operation on the netire array 100x faster than loop

[[3 5 6]
 [4 6 8]]


### handling missing values



In [15]:
# np.isnan()--> detect misssing values
# np.nan_to_num()-->missing values replacing with another number
#np.isnot()
# nan stands for not a number
import numpy as np
array5=np.array([1,2,np.nan,4,np.nan,6])
print(np.isnan(array5))



[False False  True False  True False]


### Using where to search in an array


In [2]:
import numpy as np
array6=np.array([1,2,3,4,5])
print(np.where(array6==2))

(array([1]),)
